if(WIN32)
	foreach(_CURRENT_VERSION 1.5.0 1.4.0 1.3.9 1.3.8 1.3.7 1.3.0 1.2.2 1.2.1 1.2.0)
		STRING(REPLACE "." "-" _CURRENT_VERSION_DASH ${_CURRENT_VERSION})
		FIND_PATH(LASS_CONFIG_DIR LassPythonConfig.cmake $ENV{ProgramFiles}/Cocamware/Lass-${_CURRENT_VERSION}/lib)
	endforeach()
endif(WIN32)
include(${LASS_CONFIG_DIR}/LassPythonConfig.cmake)
